---
- name: Clean up
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  loop:
    - '{{ install_base }}/{{ version }}'

- name: Ensure base install location exists
  ansible.builtin.file:
    path: '{{ install_base }}/{{ version }}'
    state: directory

- name: Install binary
  ansible.builtin.unarchive:
    src: '{{ binary_path }}'
    dest: '{{ install_base }}/{{ version }}'
    extra_opts:
      - --strip-components=1