---
- name: ensure splunk home directory exists
  ansible.builtin.file:
    path: "{{ splunk.home }}"
    state: directory
    mode: 0700

- name: install splunk from tar file
  ansible.builtin.unarchive:
    src: "{{ splunk.binary }}"
    dest: "{{ splunk.home }}"
    extra_opts:
      - --strip-components=1

- name: update zookeeper binary permission
  ansible.builtin.file:
    path: "{{ splunk.home }}"
    mode: g-rwx,o-rwx
    state: directory
    recurse: yes
