---
- name: uninstall splunk
  hosts: splunk
  collections:
    - siem.splunk
  tasks:
    - import_role:
        name: splunk-binary-uninstall
  tags:
    - uninstall

- name: install splunk
  hosts: license_master
  collections:
    - siem.splunk
  tasks:
    - import_role:
        name: splunk-binary-install
  tags:
    - install

- name: setup splunk common config
  hosts: license_master
  collections:
    - siem.splunk
  tasks:
    - import_role:
        name: splunk-common-setup
  tags:
    - common_setup