---
- name: prepare certificate from vault
  hosts: splunk
  connection: local
  collections:
    - siem.vault
  tasks:
    - ansible.builtin.import_role:
        name: vault-cert-prep
      vars:
        ssl_common_name: "{{ inventory_hostname }}"
  tags:
    - vault_cert

- name: uninstall splunk
  hosts: splunk
  collections:
    - siem.splunk
  tasks:
    - ansible.builtin.import_role:
        name: splunk-binary-uninstall
  tags:
    - uninstall

- name: install splunk
  hosts: splunk
  collections:
    - siem.splunk
  tasks:
    - ansible.builtin.import_role:
        name: splunk-binary-install
  tags:
    - install

- name: setup splunk common config
  hosts: splunk
  collections:
    - siem.splunk
  tasks:
    - ansible.builtin.import_role:
        name: splunk-common-setup
  tags:
    - common_setup

- name: install certificate
  hosts: splunk
  collections:
    - siem.splunk
  tasks:
    - ansible.builtin.import_role:
        name: splunk-cert-install
  tags:
    - install_cert

# - name: install license
#   hosts: license_master
#   collections:
#     - siem.splunk
#   tasks:
#     - ansible.builtin.import_role:
#         name: splunk-license-install
#   tags:
#     - install_license
