---
- name: install zookeeper
  hosts: zookeeper
  roles:
    - zookeeper-binary-install
  tags:
    - install

- name: update config
  hosts: zookeeper
  roles:
    - zookeeper-config-update
  tags:
    - update_config

- name: install certificate
  gather_facts: yes
  hosts: zookeeper
  roles:
    - zookeeper-certificate-install
  tags:
    - install_certificate
  environment:
    PATH: /home/ubuntu/amazon-corretto-17.0.1.12.1-linux-x64/bin:{{ ansible_env.PATH }}
