splunk:
  home: /Users/binlei/workspace/splunk
  binary: /Users/binlei/Downloads/splunk-8.2.4-87e2dda940d1-darwin-64.tgz
  ssl:
    password: please_tell_me
    email_address: cod-siem@ms.com
  pass4SymmKey: common_secret
  self_ca_path: /Users/binlei/workspace/cert
  admin_hashed_pwd: $6$LxwCgUx4yLjRxtDa$Mm35yX/60AgM0G4tMRmzrrwijX3.qvBPf7j.OgNZ.wHirgQr6tpZ8JcgFhR3cMsQGuOU4vAKUxYyU86ASkLpK1
  license: /home/jeromex/license/splunk.license
  idxc:
    pass4SymmKey: indexer cluster secret
  shc:
    pass4SymmKey: search head cluster secret