splunk:
  home: /Users/binlei/workspace/splunk
  binary: /Users/binlei/Downloads/splunk-8.2.7-2e1fca123028-darwin-64.tgz
  pass4SymmKey: common_secret
  cert_path: /Users/binlei/workspace/cert
  admin_hashed_pwd: $6$LxwCgUx4yLjRxtDa$Mm35yX/60AgM0G4tMRmzrrwijX3.qvBPf7j.OgNZ.wHirgQr6tpZ8JcgFhR3cMsQGuOU4vAKUxYyU86ASkLpK1
  license: /home/jeromex/license/splunk.license
  idxc:
    pass4SymmKey: indexer cluster secret
  shc:
    pass4SymmKey: search head cluster secret
  trail: true
